### PR TITLE
remove trever for user list

### LINKED ISSUE #35: Replace Trever
I don't really like being so dependent on Traver (#13). I think it should only be used for special one-off things that its not worth automating. It shouldn't be too hard to implement what we are doing currently with Trevor

### PR DESCRIPTION
**Pull request by MichaelStatt-S**
fixes #35 
- [x] add endpoint for member sheet
- [x] implement basic auth for sheet endpoint
- [ ] add permissions to use sheet
- [x] make custom function to use basic auth in Google sheets
- [ ] add endpoint for user log 
- [x] add endpoint for by-meeting using url parameters

### CODE REVIEW

**Comment by MichaelStatt-S** [comment]
- [ ] add activity logs (mostly copy and paste)

**Comment by yyy2356** [comment]
id like to deploy these changes on the test deployment to test everything and make sure it all works before we merge. will do the review when we do that

**Review by yyy2356 — COMMENTED** [review]
why do it via apps script instead of using the builtin importdata function? Could we not make the endpoint such that it would work with the importdata function

**Comment by MichaelStatt-S** [comment]
It _almost_ does, however, I need to implement it myself to use basic authentication. I could put it in the url, but that is even less secure. The headers for basic authentication are at least encrypted with https, the url isn't. It should have the same functionality

**Comment by yyy2356** [comment]
why dont we set it up the way openai does, where the request has a json header and the credentials can be part of the content. alternatively we could create api keys.

**Comment by MichaelStatt-S** [comment]
This should now be good. Now a priority because trever is broken

**Comment by MichaelStatt-S** [comment]
If this doesn't get reviewed soon Im overriding the branch protection to let me merge this

**Pull request merged**
